# Generated by Django 5.0.4 on 2024-04-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('tag_id', models.IntegerField()),
                ('theme_id', models.IntegerField()),
                ('theacher_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='course_theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.PositiveIntegerField()),
                ('theme_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Programming_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('task_id', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('status', models.BooleanField()),
                ('progamming_language_id', models.PositiveIntegerField()),
                ('time_of_work', models.TimeField()),
                ('user_code', models.CharField(max_length=1000)),
                ('memory_in_work', models.PositiveIntegerField()),
                ('user_output', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='submission_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.PositiveIntegerField()),
                ('score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('condition', models.CharField(max_length=1500)),
                ('input_format', models.CharField(max_length=120)),
                ('output_format', models.CharField(max_length=120)),
                ('note', models.CharField(max_length=200)),
                ('deadline', models.DateField()),
                ('max_score', models.PositiveIntegerField()),
                ('time_limit', models.PositiveIntegerField()),
                ('memoty_linit', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=500)),
                ('output', models.CharField(max_length=500)),
                ('task_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=150)),
                ('tag_id', models.PositiveIntegerField()),
                ('tasks_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='theme_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField()),
                ('discription', models.CharField(max_length=50)),
                ('tag_id', models.PositiveIntegerField()),
                ('theme_id', models.PositiveIntegerField()),
                ('teacher_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('secondname', models.CharField(max_length=30)),
                ('parentname', models.CharField(max_length=30)),
                ('is_teacher', models.BooleanField()),
                ('group', models.CharField(max_length=9)),
                ('photo', models.FileField(null=True, upload_to='uploads')),
                ('discription', models.TextField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studemt_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
            ],
        ),
    ]
